src/GESTION/GestionBundle/Entity/Adjunto.php
<?php
namespace GESTION\GestionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="GESTION\GestionBundle\Entity\AdjuntoRepository")
 * @ORM\Table(name="adjunto")
 */
class Adjunto{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $nombre;

    /**
     * @ORM\Column(type="blob", nullable=true)
     */
    protected $contenido;
	
    /**
     * @ORM\ManyToOne(targetEntity="Colaboracion", inversedBy="adjuntos")
     * @ORM\JoinColumn(name="colaboracion_id", referencedColumnName="id")
     */
    protected $colaboracion;

    /**
     * @ORM\Column(type="string", length=1)
     */
    protected $cod_estado = 'A';

    /**********************************
     * __construct
     *
     * 
     **********************************/        
	public function __construct()
	{
	}

	/**********************************
     * __toString()
     *
     * Este método sirve para poder popular los comboboxes en los forms.
     *********************************/ 
	 public function __toString()
	{
		return $this->getNombre();
	}		

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nombre
     *
     * @param string $nombre
     * @return Elemento
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;
    
        return $this;
    }

    /**
     * Get nombre
     *
     * @return string 
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set cod_estado
     *
     * @param string $codEstado
     * @return Elemento
     */
    public function setCodEstado($codEstado)
    {
        $this->cod_estado = $codEstado;
    
        return $this;
    }

    /**
     * Get cod_estado
     *
     * @return string 
     */
    public function getCodEstado()
    {
        return $this->cod_estado;
    }

    /**
     * Set contenido
     *
     * @param string $contenido
     * @return Adjunto
     */
    public function setContenido($contenido)
    {
        $this->contenido = $contenido;
    
        return $this;
    }

    /**
     * Get contenido
     *
     * @return string 
     */
    public function getContenido()
    {
        return $this->contenido;
    }
	
    public function getContenidoBlob()
    {
        return stream_get_contents( $this->contenido );
    }


    /**
     * Set colaboracion
     *
     * @param \GESTION\GestionBundle\Entity\Colaboracion $colaboracion
     * @return Adjunto
     */
    public function setColaboracion(\GESTION\GestionBundle\Entity\Colaboracion $colaboracion = null)
    {
        $this->colaboracion = $colaboracion;
    
        return $this;
    }

    /**
     * Get colaboracion
     *
     * @return \GESTION\GestionBundle\Entity\Colaboracion 
     */
    public function getColaboracion()
    {
        return $this->colaboracion;
    }
}

src/GESTION/GestionBundle/Form/ColaboracionType.php
<?php

namespace GESTION\GestionBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ColaboracionType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('cliente', 'text', array(
				'mapped'=>false, 
				'label'=>'Cliente'
			))
            ->add('idcliente', 'text', array(
				'mapped'=>false, 
				'label'=>'ID - Cliente'
			))            
            ->add('archivo', 'file', array(
				'mapped'=>false, 
				'label'=>'Archivo'
			))
            ->add('descripcion', 'textarea', array(
				'label'=>'Descripción',
				'attr'=>array('class'=>'form-control', 'attr'=>'height: 200px;')
			))
            ->add('descuento', 'text', array(
				'label'=>'Descuento'
			))
            ->add('bonificacion', 'text', array(
				'label'=>'Bonificacion'
			))
            ->add('fecha', 'text', array(
				'mapped'=>false, 
				'label'=>'Fecha',
				'attr'=>array('class'=>'datetimepicker', 'value'=>date('Y-m-d'))
			))
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'GESTION\GestionBundle\Entity\Colaboracion'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'gestion_gestionbundle_colaboracion';
    }
}

src/GESTION/GestionBundle/Controller/ColaboracionController.php
<?php

namespace GESTION\GestionBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use GESTION\GestionBundle\Entity\Colaboracion;
use GESTION\GestionBundle\Entity\ElementoColaboracion;
use GESTION\GestionBundle\Entity\Adjunto;
use GESTION\GestionBundle\Form\ColaboracionType;
use GESTION\GestionBundle\Services\SessionManager;
use JMS\DiExtraBundle\Annotation as DI;

// IMPORTACION NECESARIA PARA ARCHIVOS
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\File\File;

/**
 * Colaboracion controller.
 *
 */
class ColaboracionController extends Controller
{
	/**
	 * @var SessionManager
	 * @DI\Inject("session.manager")
	 */
	public $sessionManager;

    /**
     * Lists all Colaboracion entities.
     *
     */
    public function indexAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

		if(empty($request->get('desde'))){
			$desde = new \DateTime('NOW -30 days');
		}else{
			$desde = new \DateTime($request->get('desde'));
		}

		if(empty($request->get('hasta'))){
			$hasta = new \DateTime('NOW +1 days');
		}else{
			$hasta = new \DateTime($request->get('hasta'));
		}

        $entities = $em->getRepository('GESTIONGestionBundle:Colaboracion')->filtro($desde, $hasta);

        return $this->render('GESTIONGestionBundle:Colaboracion:index.html.twig', array(
            'entities' => $entities,
            'desde' => $desde->format('Y-m-d'),
            'hasta' => $hasta->format('Y-m-d'),
        ));
    }
    /**
     * Creates a new Colaboracion entity.
     *
     */
    public function createAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $entity = new Colaboracion();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);

		$fechastr = $form->get("fecha")->getData();

		$clientestr = $form->get("idcliente")->getData();
		if(!empty($clientestr)){
			$cliente = $em->getRepository('GESTIONGestionBundle:Cliente')->find($clientestr);
			$entity->setCliente($cliente);
		}

		if(!empty($fechastr)){
			$entity->setFecha(new \DateTime($fechastr));
		}
		$total = 0;
		if ($form->isValid()) {
			for($i = 1; $i <=30; $i++ ){
				$idelemento = $request->get("idelemento$i");
				if(!empty($idelemento)){
					$elementostocks = $em->getRepository('GESTIONGestionBundle:ElementoStock')->findBy(array('elemento'=>$idelemento), array('fecha'=>'ASC'));
					$cantidad = $request->get("cantidad$i");
					$precio = $request->get("precio$i");

					$total+= $cantidad*$precio;

					foreach($elementostocks as $elementostock){
						if($cantidad > 0 and $cantidad<=$elementostock->getStock()){
							$elementocolaboracion = new ElementoColaboracion();
							$elementocolaboracion->setElementostock($elementostock);
							$elementocolaboracion->setColaboracion($entity);
							$elementocolaboracion->setCantidad($cantidad);
							$elementocolaboracion->setPrecio($precio);
							$stock = $elementostock->getStock() - $cantidad;
							$elementostock->setStock($stock);
							$em->persist($elementocolaboracion);
							$cantidad = 0;
						}else{
							if($cantidad > 0 and $elementostock->getStock()>0){
								$elementocolaboracion = new ElementoColaboracion();
								$elementocolaboracion->setElementostock($elementostock);
								$elementocolaboracion->setColaboracion($entity);
								$elementocolaboracion->setPrecio($precio);

								$elementocolaboracion->setCantidad($elementostock->getStock());
								$cantidad = $cantidad - $elementostock->getStock();
								$elementostock->setStock(0);
								$em->persist($elementocolaboracion);
							}
						}
					}
				}
			}
			for($i = 1; $i <=9; $i++ ){
				$file = $request->files->get('adjunto'.$i);
				if($file){
					if($file->getSize()>0){
						$strm = fopen($file->getRealPath(),'rb');

						$adjunto = new Adjunto();
						$adjunto->setNombre($file->getClientOriginalName());
						$adjunto->setContenido('data:'.$file->getClientMimeType().'/'.$file->getClientOriginalExtension().';base64,'.base64_encode(stream_get_contents(($strm))));
						$adjunto->setColaboracion($entity);
						$em->persist($adjunto);
					}
				}
			}

			if($entity->getDescuento()!='' and $entity->getDescuento()!=0){
				$total = $total * (1-($entity->getDescuento()/100));
			}

			if($entity->getBonificacion()!='' and $entity->getBonificacion()>0){
				$total-=$entity->getBonificacion();
			}

			$entity->setTotal($total);

            $em->persist($entity);

            $em->flush();

            return $this->redirect($this->generateUrl('colaboracion'));
       }

        return $this->render('GESTIONGestionBundle:Colaboracion:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView(),
        ));
    }

    /**
     * Creates a form to create a Colaboracion entity.
     *
     * @param Colaboracion $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(Colaboracion $entity)
    {
        $form = $this->createForm(new ColaboracionType(), $entity, array(
            'action' => $this->generateUrl('colaboracion_create'),
            'method' => 'POST',
        ));

        $form->add('submit', 'submit', array('label' => 'Crear', 'attr'=>array('class'=>'btn btn-primary', 'style'=>'float: right')));

        return $form;
    }

    /**
     * Displays a form to create a new Colaboracion entity.
     *
     */
    public function newAction()
    {
        $entity = new Colaboracion();
        $form   = $this->createCreateForm($entity);

        return $this->render('GESTIONGestionBundle:Colaboracion:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView(),
        ));
    }

    /**
     * Finds and displays a Colaboracion entity.
     *
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('GESTIONGestionBundle:Colaboracion')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Colaboracion entity.');
        }

        return $this->render('GESTIONGestionBundle:Colaboracion:show.html.twig', array(
            'entity'      	=> $entity,
        ));
    }

    /**
     * Displays a form to edit an existing Colaboracion entity.
     *
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('GESTIONGestionBundle:Colaboracion')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Colaboracion entity.');
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        return $this->render('GESTIONGestionBundle:Colaboracion:edit.html.twig', array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    public function parcialAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('GESTIONGestionBundle:Colaboracion')->find($id);

        return $this->render('GESTIONGestionBundle:Colaboracion:parcial.html.twig', array(
            'entity'      => $entity,
        ));
    }

    public function hacerparcialAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('GESTIONGestionBundle:Colaboracion')->find($id);
		$concluido = true;
		foreach($entity->getElementoscolaboracion() as $elementocolaboracion){
			$cantidad = $request->get("cantidad".$elementocolaboracion->getId());
			if($cantidad>0){
				$nuevacantidad = $elementocolaboracion->getCantidadparcial()+$cantidad;
				$elementocolaboracion->setCantidadparcial($nuevacantidad);
				$stock = $elementocolaboracion->getElemento()->getStock() + $cantidad;
				$elementocolaboracion->getElemento()->setStock($stock);
			}

			if($elementocolaboracion->getCantidad()>$elementocolaboracion->getCantidadparcial()){
				$concluido = false;
			}
		}

		if($concluido){
			$entity->setCodEstado("R");
		}else{
			$entity->setCodEstado("P");
		}
		$em->flush();

		$this->sessionManager->addFlash("msgOk", "Entrega Parcial exitosa.");

		return $this->redirect($this->generateUrl('colaboracion'));
    }

    /**
    * Creates a form to edit a Colaboracion entity.
    *
    * @param Colaboracion $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(Colaboracion $entity)
    {
        $form = $this->createForm(new ColaboracionType(), $entity, array(
            'action' => $this->generateUrl('colaboracion_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        $form->add('submit', 'submit', array('label' => 'Modificar', 'attr'=>array('class'=>'btn btn-primary', 'style'=>'float: right')));

        return $form;
    }
    /**
     * Edits an existing Colaboracion entity.
     *
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('GESTIONGestionBundle:Colaboracion')->find($id);

        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);

		$fechastr = $editForm->get("fecha")->getData();

		if(!empty($fechastr)){
			$entity->setFecha(new \DateTime($fechastr));
		}else{
			$entity->setFecha(null);
		}

		$total = 0;
        if ($editForm->isValid()) {
			for($i = 1; $i <=30; $i++ ){
				$idelemento = $request->get("idelemento$i");
				if(!empty($idelemento)){
					$idelementocolaboracion = $request->get("idelementocolaboracion$idelemento");
					if(!empty($idelementocolaboracion)){

src/GESTION/GestionBundle/Resources/views/Colaboracion/index.html.twig
{% extends 'GESTIONGestionBundle::base.html.twig' %}

{% block body -%}
    <h1>
		Entrega de Insumos
		<a class="btn btn-primary" style="float:right;" href="{{ path('colaboracion_new') }}">
			Crear
		</a>
	</h1>
	<div style="margin-bottom: 2%;" class="row">
		<form action="{{ path('colaboracion') }}">
			<div class="col-md-12">
				<label>
					Filtro entre fechas
				</label>
			</div>
			<div class="col-md-3">
				<input placeholder="Fecha Desde" type="text" class="datetimepicker" name="desde" readonly="readonly" value="{{desde|default(app.request.get('desde'))}}" />
			</div>
			<div class="col-md-3">
				<input placeholder="Fecha Hasta" type="text" class="datetimepicker" name="hasta" readonly="readonly" value="{{hasta|default(app.request.get('hasta'))}}" />
			</div>
			<div class="col-md-6">
				<button type="submit" class="btn btn-success" style="margin-top:1px">Filtrar</button>
				<button type="button" class="btn btn-danger" style="margin-top:1px" onclick="$('.datetimepicker').val('')">Limpiar</button>
			</div>
		</form>
	</div>
	<div class="gestion">
		<table class="display" id="tablas" width="100%">
			<thead>
				<tr>
					<th>ID</th>
					<th>Cliente</th>
                    <th>Descripción</th>
                    <th>Estado</th>
					<th>Fecha</th>
					<th>Total</th>
					<th>Acciones</th>
				</tr>
			</thead>
			<tbody>
			{% for entity in entities %}
				<tr>
					<td><a href="{{ path('colaboracion_show', { 'id': entity.id }) }}">{{ entity }}</a></td>
					<td>{{ entity.cliente|default('-') }}</td>
					<td>{{ entity.descripcion|slice(0, 100) }}</td>
					<td>{{ entity.estadostr|raw }}</td>
					<td>{% if entity.fecha %}{{ entity.fecha|date('Y-m-d') }}{% endif %}</td>
					<td>$ {{ entity.total }}</td>
					<td>
					{% if entity.codEstado == 'A'%}
						<a class="btn btn-success btn-xs" href="{{ path('colaboracion_edit', { 'id': entity.id }) }}" title="Editar"><i class="fa fa-pencil"></i></a>
						<a class="btn btn-primary btn-xs" href="{{ path('colaboracion_show', { 'id': entity.id }) }}" title="Ver"><i class="fa fa-search"></i></a>
						<button class="btn btn-danger btn-xs" onclick="borrar('{{ path('colaboracion_delete', { 'id': entity.id }) }}')" title="Borrar"><i class="fa fa-times"></i></button>
                    {% endif %}
                    {% if entity.codEstado == 'PNE' %}
                        <a class="btn btn-success btn-xs" href="{{ path('colaboracion_reportarentrega', { 'id': entity.id }) }}" title="Reportar Entrega">Reportar Entrega</a>
                        <a class="btn btn-primary btn-xs" href="{{ path('colaboracion_show', { 'id': entity.id }) }}" title="Ver"><i class="fa fa-search"></i></a>
                    {% endif %}
                    {% if entity.codEstado == 'PE' %}
                        <a class="btn btn-primary btn-xs" href="{{ path('colaboracion_show', { 'id': entity.id }) }}" title="Ver"><i class="fa fa-search"></i></a>
                    {% endif %}
                    {% if entity.codEstado == 'P' %}
						<a class="btn btn-success btn-xs" href="{{ path('colaboracion_reportarpago', { 'id': entity.id }) }}" title="Reportar Pago">Reportar Pago</a>
						<a class="btn btn-primary btn-xs" href="{{ path('colaboracion_show', { 'id': entity.id }) }}" title="Ver"><i class="fa fa-search"></i></a>
						<button class="btn btn-danger btn-xs" onclick="borrar('{{ path('colaboracion_cancelar', { 'id': entity.id }) }}')" title="Cancelar"><i class="fa fa-times"></i></button>
					{% endif %}
                    {% if (entity.codEstado == 'E' or entity.codEstado == 'C') %}
                        <a class="btn btn-primary btn-xs" href="{{ path('colaboracion_show', { 'id': entity.id }) }}" title="Ver"><i class="fa fa-search"></i></a>
                    {% endif %}
					</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>

	<script>
		$("document").ready(function(){
			table.order([4, 'desc']).draw();
		});
	</script>
{% endblock %}

src/GESTION/GestionBundle/Resources/views/Colaboracion/show.html.twig
{% extends 'GESTIONGestionBundle::base.html.twig' %}

{% block body -%}
    <h1>
		Entrega "{{entity}}" - {{entity.estadostr|raw}}
		<a class="btn btn-default" style="float:right;" href="{{ path('colaboracion') }}">
			Volver
		</a>
	</h1>
    <table class="table">
        <tbody>
            <tr>
                <th>Cliente</th>
                <td><a href="{{path('cliente_show', {id:entity.cliente.id})}}" target="_blank">{{ entity.cliente }}</a></td>
                <th>Fecha</th>
                <td>{{ entity.fecha|date('Y-m-d H:i:s') }}</td>
                <th>Total</th>
                <td>$ {{ entity.total }}</td>
            </tr>
            <tr>
                <th>Tipo de Venta</th>
                <td>{{ entity.tipo }}</td>
                <th>Descuento</th>
                <td>% {{ entity.descuento }}</td>
                <th>Bonificación</th>
                <td>$ {{ entity.bonificacion }}</td>
            </tr>
			<tr>
                <th colspan="6">Descripción</th>
            </tr>
            <tr>
                <td colspan="6">{{ entity.descripcion }}</td>
            </tr>
            <tr>
            </tr>
        </tbody>
    </table>
	<div class="col-md-12">
		<h3>
		Productos en la Entrega
		</h3>
		<hr />
	</div>
	<div class="col-md-12">
		<table class="display" id="tablaSF" width="100%">
			<thead>
				<tr>
					<th>Elemento</th>
					<th>Tipo y N° Fact.</th>
					<th>Cantidad</th>
					<th>Precio</th>
				</tr>
			</thead>
			<tbody>
			{% for elementocolaboracion in entity.elementoscolaboracion %}
				<tr>
					<td>
						<a href="{{ path('elemento_show', { 'id': elementocolaboracion.elementostock.elemento.id }) }}">
							{{ elementocolaboracion.elementostock.elemento }} - {{ elementocolaboracion.elementostock.elemento.nombre }}
						</a>
					</td>
					<td>F. {{elementocolaboracion.elementostock.tipofactura}} - N° {{elementocolaboracion.elementostock.factura}}</td>
					<td>{{elementocolaboracion.cantidad}}</td>
					<td>$ {{elementocolaboracion.precio}}</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>
	<div class="col-md-12">
		<h3>
		Adjuntos
		</h3>
		<hr />
	</div>
	<div class="col-md-12">
		<table class="table" width="100%">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>Archivo</th>
				</tr>
			</thead>
			<tbody>
			{% for adjunto in entity.adjuntos %}
				<tr>
					<td>{{adjunto.nombre}}</td>
					<td>
						<a href="{{ adjunto.contenidoBlob }}" download="{{adjunto.nombre}}" target="_blank" title="{{adjunto.nombre}}" alt="{{adjunto.nombre}}" name="{{adjunto.nombre}}">
						<i class="fa fa-download"></i> {{adjunto.nombre}}

						</a>
					</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>

	<script>
		$("document").ready(function(){
			table.order([0, 'asc']).draw();
		});
	</script>
{% endblock %}