src/GESTION/GestionBundle/Entity/Elemento.php
<?php
namespace GESTION\GestionBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="GESTION\GestionBundle\Entity\ElementoRepository")
 * @ORM\Table(name="elemento")
 */
class Elemento{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $nombre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $slug;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $codigo;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $novedad = false;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $visible = false;

    /**
     * @ORM\Column(type="boolean")
     */
    protected $destacado = false;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $stockminimo = 0;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    protected $precio = 0;

    /**
     * @ORM\Column(type="string", length=4000, nullable=true)
     */
    protected $descripcion;

    /**
     * @ORM\Column(type="blob", nullable=true)
     */
    protected $imagen;

    /**
     * @ORM\Column(type="blob", nullable=true)
     */
    protected $imagendos;

    /**
     * @ORM\Column(type="blob", nullable=true)
     */
    protected $imagentres;

    /**
     * @ORM\OneToMany(targetEntity="ElementoStock", mappedBy="elemento")
     */
    protected $stocks;

    /**
     * @ORM\ManyToOne(targetEntity="Categoria", inversedBy="elementos")
     * @ORM\JoinColumn(name="categoria_id", referencedColumnName="id")
     */
    protected $categoria;

    /**
     * @ORM\Column(type="string", length=1)
     */
    protected $cod_estado = 'A';

    /**********************************
     * __construct
     *
     *
     **********************************/
	public function __construct()
	{
		$this->stocks = new ArrayCollection();
	}

	/**********************************
     * __toString()
     *
     * Este método sirve para poder popular los comboboxes en los forms.
     *********************************/
	 public function __toString()
	{
		return $this->getCodigo();
	}

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return Elemento
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Set nombre
     *
     * @param string $nombre
     * @return Elemento
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * Get nombre
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Get stock
     *
     * @return integer
     */
    public function getStock()
    {
		$stocktotal = 0;
		foreach($this->stocks as $stock){
			$stocktotal+=$stock->getStock();
		}
        return $stocktotal;
    }

    /**
     * Set descripcion
     *
     * @param string $descripcion
     * @return Elemento
     */
    public function setDescripcion($descripcion)
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    /**
     * Get descripcion
     *
     * @return string
     */
    public function getDescripcion()
    {
        return $this->descripcion;
    }

    /**
     * Set imagen
     *
     * @param string $imagen
     * @return Elemento
     */
    public function setImagen($imagen)
    {
        $this->imagen = $imagen;

        return $this;
    }

    /**
     * Get imagen
     *
     * @return string
     */
    public function getImagen()
    {
        return $this->imagen;
    }

    public function getImagenBlob()
    {
		if(!empty($this->imagen)){
			return stream_get_contents( $this->imagen );
		}else{
			return "";
		}
    }

    /**
     * Set imagendos
     *
     * @param string $imagendos
     * @return Elemento
     */
    public function setImagendos($imagendos)
    {
        $this->imagendos = $imagendos;

        return $this;
    }

    /**
     * Get imagendos
     *
     * @return string
     */
    public function getImagendos()
    {
        return $this->imagendos;
    }

    public function getImagendosBlob()
    {
		if(!empty($this->imagendos)){
			return stream_get_contents( $this->imagendos );
		}else{
			return "";
		}
    }

    /**
     * Set imagentres
     *
     * @param string $imagentres
     * @return Elemento
     */
    public function setImagentres($imagentres)
    {
        $this->imagentres = $imagentres;

        return $this;
    }

    /**
     * Get imagentres
     *
     * @return string
     */
    public function getImagentres()
    {
        return $this->imagentres;
    }

    public function getImagentresBlob()
    {
		if(!empty($this->imagentres)){
			return stream_get_contents( $this->imagentres );
		}else{
			return "";
		}
    }

    /**
     * Set cod_estado
     *
     * @param string $codEstado
     * @return Elemento
     */
    public function setCodEstado($codEstado)
    {
        $this->cod_estado = $codEstado;

        return $this;
    }

    /**
     * Get cod_estado
     *
     * @return string
     */
    public function getCodEstado()
    {
        return $this->cod_estado;
    }

    /**
     * Set codigo
     *
     * @param string $codigo
     * @return Elemento
     */
    public function setCodigo($codigo)
    {
        $this->codigo = $codigo;

        return $this;
    }

    /**
     * Get codigo
     *
     * @return string
     */
    public function getCodigo()
    {
        return $this->codigo;
    }

    /**
     * Set categoria
     *
     * @param \GESTION\GestionBundle\Entity\Categoria $categoria
     * @return Elemento
     */
    public function setCategoria(\GESTION\GestionBundle\Entity\Categoria $categoria = null)
    {
        $this->categoria = $categoria;

        return $this;
    }

    /**
     * Get categoria
     *
     * @return \GESTION\GestionBundle\Entity\Categoria
     */
    public function getCategoria()
    {
        return $this->categoria;
    }

    /**
     * Set stockminimo
     *
     * @param integer $stockminimo
     * @return Elemento
     */
    public function setStockminimo($stockminimo)
    {
        $this->stockminimo = $stockminimo;

        return $this;
    }

    /**
     * Get stockminimo
     *
     * @return integer
     */
    public function getStockminimo()
    {
        return $this->stockminimo;
    }

    /**
     * Set precio
     *
     * @param float $precio
     * @return Elemento
     */
    public function setPrecio($precio)
    {
        $this->precio = $precio;

        return $this;
    }

    /**
     * Get precio
     *
     * @return float
     */
    public function getPrecio()
    {
        return $this->precio;
    }

    /**
     * Set dependenciaorigen
     *
     * @param string $dependenciaorigen
     * @return Categoria
     */
    public function setDependenciaorigen($dependenciaorigen)
    {
        $this->dependenciaorigen = $dependenciaorigen;

        return $this;
    }

    /**
     * Get dependenciaorigen
     *
     * @return string
     */
    public function getDependenciaorigen()
    {
        return $this->dependenciaorigen;
    }

    /**
     * Add stocks
     *
     * @param \GESTION\GestionBundle\Entity\ElementoStock $stocks
     * @return Elemento
     */
    public function addStock(\GESTION\GestionBundle\Entity\ElementoStock $stocks)
    {
        $this->stocks[] = $stocks;

        return $this;
    }

    /**
     * Remove stocks
     *
     * @param \GESTION\GestionBundle\Entity\ElementoStock $stocks
     */
    public function removeStock(\GESTION\GestionBundle\Entity\ElementoStock $stocks)
    {
        $this->stocks->removeElement($stocks);
    }

    /**
     * Get stocks
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getStocks()
    {
        return $this->stocks;
    }

    /**
     * Set novedad
     *
     * @param boolean $novedad
     * @return Elemento
     */
    public function setNovedad($novedad)
    {
        $this->novedad = $novedad;

        return $this;
    }

    /**
     * Get novedad
     *
     * @return boolean
     */
    public function getNovedad()
    {
        return $this->novedad;
    }

    /**
     * Set destacado
     *
     * @param boolean $destacado
     * @return Elemento
     */
    public function setDestacado($destacado)
    {
        $this->destacado = $destacado;

        return $this;
    }

    /**
     * Get destacado
     *
     * @return boolean
     */
    public function getDestacado()
    {
        return $this->destacado;
    }

    /**
     * Set visible
     *
     * @param boolean $visible
     * @return Elemento
     */
    public function setVisible($visible)
    {
        $this->visible = $visible;

        return $this;
    }

    /**
     * Get visible
     *
     * @return boolean
     */
    public function getVisible()
    {
        return $this->visible;
    }
}

src/GESTION/GestionBundle/Form/ElementoType.php
<?php

namespace GESTION\GestionBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\HttpFoundation\Request;


class ElementoType extends AbstractType
{
	
	/**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
	private $value;
	public function __construct($iddep){
		$this->value = $iddep;
	}

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
		$iddep = $this->value;
        $builder
            ->add('nombre')
            ->add('codigo')
			->add('categoria', 'entity', array (
				'class' => 'GESTIONGestionBundle:Categoria',
				'label' => 'Categoria',
				'query_builder' => function (\GESTION\GestionBundle\Entity\CategoriaRepository $repository)  use ( $iddep )
					 {
						 return $repository->createQueryBuilder('u')->where('u.cod_estado = :ACTIVO')->orderBy('u.nombre', 'asc')->setParameter(':ACTIVO', 'A');											 					 	 }
					))
            ->add('stockminimo', 'text', array('label'=>'Stock Mínimo'))
            ->add('novedad')
            ->add('destacado')
            ->add('precio', 'text', array('label'=>'Precio'))
            ->add('descripcion', 'textarea', array('attr'=>array('class'=>'form-control')))
            ->add('imagen', 'file', array('label'=>'Imagen Principal', 'mapped'=>false, 'attr'=>array('accept'=>'image/*')))
            ->add('imagendos', 'file', array('label'=>'Imagen dos', 'mapped'=>false, 'attr'=>array('accept'=>'image/*')))
            ->add('imagentres', 'file', array('label'=>'Imagen tres', 'mapped'=>false, 'attr'=>array('accept'=>'image/*')))
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'GESTION\GestionBundle\Entity\Elemento'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'gestion_gestionbundle_elemento';
    }
}

src/GESTION/GestionBundle/Resources/views/Elemento/edit.html.twig
{% extends 'GESTIONGestionBundle::base.html.twig' %}

{% block body -%}
    <h1>
		Edición de {{entity.nombre}}
		<a class="btn btn-default" style="float:right;" href="{{ path('elemento') }}">
			Volver
		</a>
	</h1>
	<div class="col-md-6 col-md-offset-3 gestion">
		{{ form(edit_form) }}
		<div class="col-md-12 imgDownload">
			{% if entity.imagen %}
				<br/>
				<a href="{{entity.imagenBlob}}" download="{{entity.slug}}-principal.jpg">Imagen Principal <i class="fa fa-download"></i></a>
			{% endif %}
			{% if entity.imagendos %}
				<br/>
				<a href="{{entity.imagendosBlob}}" download="{{entity.slug}}-secundaria.jpg">Imagen Secundaria <i class="fa fa-download"></i></a>
			{% endif %}
			{% if entity.imagentres %}
				<br/>
				<a href="{{entity.imagentresBlob}}" download="{{entity.slug}}-tercera.jpg">Tercer Imagen <i class="fa fa-download"></i></a>
			{% endif %}
		</div>
	</div>

	<script>
		$(document).ready(function(){
			$('#gestion_gestionbundle_elemento_destacado,#gestion_gestionbundle_elemento_novedad').removeAttr('required');
		});
	</script>
	<style>
		.imgDownload{
		    font-size: 1.2em;
			text-align: center;
			border: 1px solid;
			border-color: #d0d0d0;
			border-radius: 5px;
			padding-bottom: 20px;
			margin-top: 1em;
		}
	</style>
{% endblock %}

src/GESTION/GestionBundle/Resources/views/Elemento/index.html.twig
{% extends 'GESTIONGestionBundle::base.html.twig' %}

{% block body -%}
    <h1>
		Listado de Productos
		<a class="btn btn-primary" style="float:right;" href="{{ path('elemento_new') }}">
			Crear
		</a>
	</h1>
	<div class="gestion">
		<table class="display" id="tablas">
			<thead>
				<tr>
					<th>ID</th>
					<th>Nombre</th>
					<th>Categoría</th>
					<th>Stock</th>
					<th>Precio</th>
					<th>Acciones</th>
				</tr>
			</thead>
			<tbody>
			{% for entity in entities %}
				<tr>
					<td>{{ entity.codigo }}</td>
					<td><a href="{{ path('elemento_show', { 'id': entity.id }) }}">{{ entity.nombre }}</a></td>
					<td>{{ entity.categoria }}</td>
					<td>{{ entity.stock }}</td>
					<td>${{ entity.precio }}</td>
					<td>
					{% if entity.codEstado == 'A' %}
						<a class="btn btn-info btn-xs" href="{{ path('elementostock', { 'id': entity.id }) }}" title="Manejo de Stock"><i class="fa fa-plus"></i></a>
						{% if entity.visible %}
						<a class="btn btn-default btn-xs" href="{{ path('elemento_novisible', { 'id': entity.id }) }}" title="No Visible"><i class="fa fa-eye-slash"></i></a>
						{% else %}
						<a class="btn btn-default btn-xs" href="{{ path('elemento_visible', { 'id': entity.id }) }}" title="Hacer Visible"><i class="fa fa-eye"></i></a>
						{% endif %}
						<a class="btn btn-success btn-xs" href="{{ path('elemento_edit', { 'id': entity.id }) }}" title="Editar"><i class="fa fa-pencil"></i></a>
						<a class="btn btn-primary btn-xs" href="{{ path('elemento_show', { 'id': entity.id }) }}" title="Ver"><i class="fa fa-search"></i></a>
						<a class="btn btn-danger btn-xs" href="{{ path('elemento_delete', { 'id': entity.id }) }}" title="Borrar"><i class="fa fa-times"></i></a>
					{% else %}
						<a class="btn btn-primary btn-xs" href="{{ path('elemento_activar', { 'id': entity.id }) }}" title="Activar">Activar</a>
					{% endif %}
					</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>
{% endblock %}

src/GESTION/GestionBundle/Resources/views/Elemento/listado.html.twig
{% extends 'GESTIONGestionBundle::base.html.twig' %}

{% block body -%}
    <h1>
		Productos en Stock
	</h1>
	<div class="gestion">
		<table class="display" id="tabla" width="100%">
			<thead>
				<tr>
					<th>Código</th>
					<th>Nombre</th>
					<th>Categoría</th>
					<th>En Stock</th>
				</tr>
			</thead>
			<tbody>
			{% for entity in entities %}
				<tr>
					<td>{{ entity.codigo }}</td>
					<td>{{ entity.nombre }}</td>
					<td>{{ entity.categoria }}</td>
					<td>{{ entity.stock }}</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>

	<script>
			$('#tabla').DataTable( {
				"paging":   false,
				"ordering": false,
				"info":     false,
				"filter": false,
				"scrollY":  "480px",
				dom: 'Bfrtip',
				buttons: [
					{
						extend: 'excelHtml5',
						filename: 'Listado de Insumos',
						text: 'Guardar en excel',
						footer: true,
						exportOptions: {
							modifier: {
								page: 'current'
							}
						}
					},
					{
						extend: 'pdfHtml5',
						message: 'Listado en Insumos',
						filename: 'Listado de Insumos',
						text: 'Guardar en PDF',
						footer: true,
//						orientation: 'landscape',
//						pageSize: 'LEGAL',
						exportOptions: {
							modifier: {
								page: 'current'
							}
						},
						customize: function ( doc ) {
							console.log(doc);
							doc.content[2].table.widths = '*';

							var rowCount = document.getElementById("tabla").rows.length;
							for (i = 0; i < rowCount; i++) {
								doc.content[2].table.body[i][0].alignment = 'center';
								doc.content[2].table.body[i][1].alignment = 'center';
								doc.content[2].table.body[i][2].alignment = 'center';
								doc.content[2].table.body[i][3].alignment = 'center';
							};
							
							var cols = [];
							cols[0] = {text: 'Div. Sistemas contra el narcotrafico', alignment: 'left', margin:[20] };
							var objFooter = {};
							objFooter['columns'] = cols;
							doc['footer'] = objFooter;
						}
					}		
				],
				"oLanguage": {
					"sSearch": "Buscar:",
					"sEmptyTable": 	   "No se encontraron registros.",			
					"sProcessing":     "Procesando...",
					"sLengthMenu":     "Mostrar _MENU_ registros",
					"sZeroRecords":    "No se encontraron resultados",
					"sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
					"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
					"sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
					"sInfoPostFix":    "",
					"sSearch":         "Buscar:",
					"sUrl":            "",
					"sInfoThousands":  ",",
					"sLoadingRecords": "Cargando..."
				}
				
			} );
	</script>
{% endblock %}

src/GESTION/GestionBundle/Resources/views/Elemento/listadocategoria.html.twig
{% extends 'GESTIONGestionBundle::base.html.twig' %}

{% block body -%}
    <h1>
		Insumos en Stock por Categoría
	</h1>
	<div class="gestion">
		<table class="display" id="tabla" width="100%">
			<thead>
				<tr>
					<th>Categoría</th>
					<th>En Stock</th>
				</tr>
			</thead>
			<tbody>
			{% for entity in entities %}
				<tr>
					<td>{{ entity.nombrecategoria }}</td>
					<td>{{ entity.stock }}</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>

	<script>
			$('#tabla').DataTable( {
				"paging":   false,
				"ordering": false,
				"info":     false,
				"filter": false,
				"scrollY":  "480px",
				dom: 'Bfrtip',
				buttons: [
					{
						extend: 'excelHtml5',
						filename: 'Listado de Elementos',
						text: 'Guardar en excel',
						footer: true,
						exportOptions: {
							modifier: {
								page: 'current'
							}
						}
					},
					{
						extend: 'pdfHtml5',
						message: 'Listado en Elementos',
						filename: 'Listado de Elementos',
						text: 'Guardar en PDF',
						footer: true,
//						orientation: 'landscape',
//						pageSize: 'LEGAL',
						exportOptions: {
							modifier: {
								page: 'current'
							}
						},
						customize: function ( doc ) {
							console.log(doc);
							doc.content[2].table.widths = '*';

							var rowCount = document.getElementById("tabla").rows.length;
							for (i = 0; i < rowCount; i++) {
								doc.content[2].table.body[i][0].alignment = 'center';
								doc.content[2].table.body[i][1].alignment = 'center';
								doc.content[2].table.body[i][2].alignment = 'center';
								doc.content[2].table.body[i][3].alignment = 'center';
							};
							
							var cols = [];
							cols[0] = {text: 'Div. Sistemas contra el narcotrafico', alignment: 'left', margin:[20] };
							var objFooter = {};
							objFooter['columns'] = cols;
							doc['footer'] = objFooter;
						}
					}		
				],
				"oLanguage": {
					"sSearch": "Buscar:",
					"sEmptyTable": 	   "No se encontraron registros.",			
					"sProcessing":     "Procesando...",
					"sLengthMenu":     "Mostrar _MENU_ registros",
					"sZeroRecords":    "No se encontraron resultados",
					"sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
					"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
					"sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
					"sInfoPostFix":    "",
					"sSearch":         "Buscar:",
					"sUrl":            "",
					"sInfoThousands":  ",",
					"sLoadingRecords": "Cargando..."
				}
				
			} );
	</script>
{% endblock %}

src/GESTION/GestionBundle/Resources/views/Elemento/new.html.twig
{% extends 'GESTIONGestionBundle::base.html.twig' %}

{% block body -%}
    <h1>
		Crear Producto
		<a class="btn btn-default" style="float:right;" href="{{ path('elemento') }}">
			Volver
		</a>
	</h1>
	<div class="col-md-6 col-md-offset-3 gestion">
		{{ form_start(form) }}
		
		{{ form_end(form) }}
	</div>
	<script>
		$(document).ready(function(){
			$('#gestion_gestionbundle_elemento_destacado,#gestion_gestionbundle_elemento_novedad').removeAttr('required');
		});
	</script>
{% endblock %}

src/GESTION/GestionBundle/Resources/views/Elemento/show.html.twig
{% extends 'GESTIONGestionBundle::base.html.twig' %}

{% block body -%}
    <h1>
		{{entity.nombre}}
		<a class="btn btn-default" style="float:right;" href="{{ path('elemento') }}">
			Volver
		</a>
	</h1>
    <div class="gestion col-md-8 col-md-offset-2">
		<table class="table">
			<tbody>
				<tr>
					<th>Código</th>
					<td>{{ entity.codigo }}</td>
				</tr>
				<tr>
					<th>Categoría</th>
					<td>{{ entity.categoria }}</td>
				</tr>
				<tr>
					<th>Stock Total</th>
					<td>{{ entity.stock }}</td>
				</tr>
				<tr>
					<th>Stock Mínimo</th>
					<td>{{ entity.stockminimo }}</td>
				</tr>
				<tr>
					<th>Descripción</th>
					<td>{{ entity.descripcion|nl2br }}</td>
				</tr>
				<tr>
					<th>Imagen</th>
					<td><img style='width: 50%;' src="{{ entity.imagenBlob }}" /></td>
				</tr>
			</tbody>
		</table>
	</div>
{% endblock %}